name: Build and Test

on: [ push ]

env:
  NODE_ENV: ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: docker pull --quiet postgres:17-alpine
      - run: docker pull --quiet postgres:18-alpine

      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: npm

      - run: npm ci
      - run: npm run test
      - run: npm run build
