name: Build and Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt-get -qq update
          sudo apt-get -qq install --yes docker-compose
          # Pull image to avoid timeouts when running the integration tests
          docker pull --quiet postgres:18

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 26

      - run: npm ci
#      - run: npm i --no-save @biomejs/cli-linux-x64 @swc/core @rollup/rollup-linux-x64-gnu
      - run: npm test:ci
      - run: npm build
